## NumPy Basics
### create array

In [31]:
import numpy as np #from numpy import * --> no need for np. (array([(...)]))

a = np.array([(1, 2, 3), (4, 5, 6.7)])
print(type(a))

<class 'numpy.ndarray'>


In [15]:
print(a.ndim) #prints number of dimensions

2


In [16]:
print(a.shape) # number of rows, number of columns

(2, 3)


In [17]:
print(a.size) # number of elements

6


In [32]:
print(a.dtype) # prints datatype

float64


In [19]:
print(a.itemsize) # bytes

8


#create 'empty' array - pre-allocation


In [33]:
zeros( (3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
b = zeros((2, 4))

In [35]:
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
