# NumPy basics continued

In [13]:
import numpy as np
d = np.arange(10, 30, 5)
print(type(d))
print(d)
d.dtype

<class 'numpy.ndarray'>
[10 15 20 25]


dtype('int32')

In [6]:
d = np.arange(10, 1, -0.5)
print(d)

[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]


In [15]:
# note the difference to arange above!
d = np.linspace(10, 30, 5)
print(d)
d.dtype

[10. 15. 20. 25. 30.]


dtype('float64')

In [20]:
d = np.arange(12)
d = d.reshape(3, 4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
d = np.arange(24)
d = d.reshape(2, 3, 4)
print(d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [34]:
d1 = np.arange(12)
d1 = d1.reshape(3, 4)
d2 = np.ones((3, 4))
d2[1, 1] = 10

d3 = d1-d2
d4 = d1**d2
print(d1)
print(d2)
print(d4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1.  1.  1.  1.]
 [ 1. 10.  1.  1.]
 [ 1.  1.  1.  1.]]
[[0.000000e+00 1.000000e+00 2.000000e+00 3.000000e+00]
 [4.000000e+00 9.765625e+06 6.000000e+00 7.000000e+00]
 [8.000000e+00 9.000000e+00 1.000000e+01 1.100000e+01]]
