## NumPy Basics
### create array

In [8]:
import numpy as np #from numpy import * --> no need for np. (array([(...)]))

a = np.array([(1, 2, 3), (4, 5, 6.7)])
print(type(a))

<class 'numpy.ndarray'>


### basic commands


In [9]:
print(a.ndim) #prints number of dimensions

2


In [10]:
print(a.shape) # number of rows, number of columns

(2, 3)


In [11]:
print(a.size) # number of elements

6


In [12]:
print(a.dtype) # prints datatype

float64


In [13]:
print(a.itemsize) # bytes

8


### create 'empty' array - pre-allocation


In [26]:
np.zeros( (3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
b = np.zeros((2, 4)) #also works with 'ones'

In [28]:
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
np.empty( (3, 4) ) #creates an array with random numbers

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

##### random numbers exkurs -- see extra python tutorial on random numbers


In [30]:
np.random.rand(3, 2) # alternatively import numpy.random

array([[0.31180117, 0.28937378],
       [0.05101616, 0.51012448],
       [0.36213625, 0.69476427]])

In [31]:
np.random.randn(5, 7) 

array([[ 0.45448537, -1.63914638, -1.85971154,  0.50672145,  0.03359857,
        -0.70385824, -1.73383435],
       [-1.66396031, -0.01814678,  0.71604526,  1.57347946,  0.43390036,
         0.41332221,  0.50979716],
       [ 0.63809383, -0.47702622, -0.34881612, -1.84106705, -0.55035628,
         0.29426723,  1.85450851],
       [ 2.80265568, -1.35334518,  1.42190792, -1.05030001, -0.91064477,
         3.15334091,  1.06292516],
       [ 0.53923291,  1.24433061,  0.39649094,  1.13837415, -1.41267539,
         0.81151849,  0.64211143]])

### create and reshape arrays

In [32]:
import numpy as np
d = np.arange(10, 30, 5)
print(type(d))
print(d)
d.dtype

<class 'numpy.ndarray'>
[10 15 20 25]


dtype('int64')

In [33]:
d = np.arange(10, 1, -0.5)
print(d)

[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]


In [34]:
# note the difference to arange above!
d = np.linspace(10, 30, 5)
print(d)
d.dtype

[10. 15. 20. 25. 30.]


dtype('float64')

In [35]:
d = np.arange(12)
d = d.reshape(3, 4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
d = np.arange(24)
d = d.reshape(2, 3, 4)
print(d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Element-wise arithmetics with arrays


In [61]:
d1 = np.arange(12)
d1 = d1.reshape(3, 4)
d2 = np.ones((3, 4))
d2[1, 1] = 10

d3 = d1-d2
d4 = d1**d2
print(d1)
print(d2)
print(d4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1.  1.  1.  1.]
 [ 1. 10.  1.  1.]
 [ 1.  1.  1.  1.]]
[[0.000000e+00 1.000000e+00 2.000000e+00 3.000000e+00]
 [4.000000e+00 9.765625e+06 6.000000e+00 7.000000e+00]
 [8.000000e+00 9.000000e+00 1.000000e+01 1.100000e+01]]


In [62]:
print(d1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [63]:
d1 += 3 # works with +, -, *, /
print(d1)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [64]:
d1.sum() # .min(), .max(), .cumsum(axis=1/2)

102

##### column/row-wise summation

In [67]:
d5 = d1.sum(axis=0) # column-wise summation
d6 = d1.sum(axis=1) # row-wise summation
print(d5)
print(d6)

[21 24 27 30]
[18 34 50]


### Matric product using dot function

In [50]:
m1 = np.random.random((4, 4))
m2 = np.linspace(17, 33, 16).reshape(4, 4)
print(m1)
print(m2)
print('-----m3-----')
m3 = np.dot(m1, m2)
print(m3)

[[0.82881953 0.70174744 0.01461229 0.43367115]
 [0.90836386 0.92832677 0.19987354 0.3075152 ]
 [0.7510505  0.94790276 0.26590152 0.4628132 ]
 [0.9074538  0.0659494  0.67760645 0.17595674]]
[[17.         18.06666667 19.13333333 20.2       ]
 [21.26666667 22.33333333 23.4        24.46666667]
 [25.53333333 26.6        27.66666667 28.73333333]
 [29.8        30.86666667 31.93333333 33.        ]]
-----m3-----
[[42.31026136 44.42103512 46.53180887 48.64258263]
 [49.45199225 51.95234358 54.45269491 56.95304623]
 [53.50777599 56.0972885  58.68680101 61.27631351]
 [39.37430068 41.32306483 43.27182897 45.22059312]]
