## NumPy Basics
### create array

In [1]:
import numpy as np #from numpy import * --> no need for np. (array([(...)]))

a = np.array([(1, 2, 3), (4, 5, 6.7)])
print(type(a))

<class 'numpy.ndarray'>


### basic commands


In [2]:
print(a.ndim) #prints number of dimensions

2


In [3]:
print(a.shape) # number of rows, number of columns

(2, 3)


In [4]:
print(a.size) # number of elements

6


In [5]:
print(a.dtype) # prints datatype

float64


In [6]:
print(a.itemsize) # bytes

8


### create 'empty' array - pre-allocation


In [7]:
np.zeros( (3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
b = np.zeros((2, 4)) #also works with 'ones'

In [9]:
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
np.empty( (3, 4) ) #creates an array with random numbers

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

##### random numbers exkurs -- see extra python tutorial on random numbers


In [11]:
np.random.rand(3, 2) # alternatively import numpy.random

array([[0.7231155 , 0.8613837 ],
       [0.94331327, 0.50793395],
       [0.62039163, 0.66371749]])

In [12]:
np.random.randn(5, 7) 

array([[ 1.42928849, -0.49296272,  0.60234121, -0.85164711, -0.32535486,
        -1.38551047,  1.45691761],
       [ 0.84893857,  0.91265982, -0.11053998, -0.4282406 ,  0.06190248,
         0.72045787,  0.08207509],
       [-0.00547012,  0.38546953, -0.95624242, -0.48066444, -0.48714805,
        -0.70678316, -1.001593  ],
       [ 0.7215912 ,  1.20915896,  0.27604879, -1.00047374,  0.70783754,
         0.13283079,  0.69368188],
       [ 1.26442055, -0.75259917, -1.09966769, -0.03011836, -1.91266154,
        -0.48882023, -1.83263958]])

### create and reshape arrays

In [13]:
import numpy as np
d = np.arange(10, 30, 5)
print(type(d))
print(d)
d.dtype

<class 'numpy.ndarray'>
[10 15 20 25]


dtype('int32')

In [14]:
d = np.arange(10, 1, -0.5)
print(d)

[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]


In [15]:
# note the difference to arange above!
d = np.linspace(10, 30, 5)
print(d)
d.dtype

[10. 15. 20. 25. 30.]


dtype('float64')

In [16]:
d = np.arange(12)
d = d.reshape(3, 4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
d = np.arange(24)
d = d.reshape(2, 3, 4)
print(d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Element-wise arithmetics with arrays


In [18]:
d1 = np.arange(12)
d1 = d1.reshape(3, 4)
d2 = np.ones((3, 4))
d2[1, 1] = 10

d3 = d1-d2
d4 = d1**d2
print(d1)
print(d2)
print(d4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1.  1.  1.  1.]
 [ 1. 10.  1.  1.]
 [ 1.  1.  1.  1.]]
[[0.000000e+00 1.000000e+00 2.000000e+00 3.000000e+00]
 [4.000000e+00 9.765625e+06 6.000000e+00 7.000000e+00]
 [8.000000e+00 9.000000e+00 1.000000e+01 1.100000e+01]]


In [19]:
print(d1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
d1 += 3 # works with +, -, *, /
print(d1)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [21]:
d1.sum() # .min(), .max(), .cumsum(axis=1/2)

102

##### column/row-wise summation

In [22]:
d5 = d1.sum(axis=0) # column-wise summation
d6 = d1.sum(axis=1) # row-wise summation
print(d5)
print(d6)

[21 24 27 30]
[18 34 50]


### Matric product using dot function

In [23]:
m1 = np.random.random((4, 4))
m2 = np.linspace(17, 33, 16).reshape(4, 4)
print(m1)
print(m2)
print('-----m3-----')
m3 = np.dot(m1, m2)
print(m3)

[[0.27400331 0.61558162 0.4254761  0.86939948]
 [0.96682232 0.95492757 0.66461223 0.00569771]
 [0.3230131  0.19334915 0.68632631 0.68532966]
 [0.82565474 0.04922762 0.98256476 0.430869  ]]
[[17.         18.06666667 19.13333333 20.2       ]
 [21.26666667 22.33333333 23.4        24.46666667]
 [25.53333333 26.6        27.66666667 28.73333333]
 [29.8        30.86666667 31.93333333 33.        ]]
-----m3-----
[[54.52135281 56.85144401 59.18153521 61.51162642]
 [53.88366303 56.64852685 59.41339067 62.17825448]
 [47.55013686 49.56402296 51.57790906 53.59179515]
 [53.01108788 55.45195842 57.89282895 60.33369949]]


### Indexing, slicing, iterating

In [33]:
d1 = np.linspace(2, 20, 10, dtype=int)
print(d1)
print(d1[2:5])

[ 2  4  6  8 10 12 14 16 18 20]
[ 6  8 10]


In [38]:
d2 = d1
# line below in words: replace elements at positions 0 to 5 (the latter exclusive!),
# in steps of 2, by 100
d2[0:5:2] = 100
print(d2)

[100   4 100   8 100  12  14  16  18  20]


In [41]:
# revert number of elements
print(d1[: :-1])

[ 20  18  16  14  12 100   8 100   4 100]


In [50]:
for i in d1:
    print(i**4)

100000000
256
100000000
4096
100000000
20736
38416
65536
104976
160000


In [57]:
d2 = np.linspace(0,11,12,dtype=int).reshape(3,4)
print(d2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [59]:
# one specific element
print(d2[1, 2])

6


In [63]:
# lower right 'corner' (remember the 'exclusive' thing)
print(d2[1:3, 2:4])

[[ 6  7]
 [10 11]]


In [67]:
# an entire column
print(d2[:,2])

[ 2  6 10]


In [81]:
d2[(0, 2),:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [86]:
d3 = np.linspace(0, 9, 24).reshape(4, 3, 2)
print(d3.shape)
d4 = d3[0,...]
print(d3)
print("------------------------------")
print(d4)

(4, 3, 2)
[[[0.         0.39130435]
  [0.7826087  1.17391304]
  [1.56521739 1.95652174]]

 [[2.34782609 2.73913043]
  [3.13043478 3.52173913]
  [3.91304348 4.30434783]]

 [[4.69565217 5.08695652]
  [5.47826087 5.86956522]
  [6.26086957 6.65217391]]

 [[7.04347826 7.43478261]
  [7.82608696 8.2173913 ]
  [8.60869565 9.        ]]]
------------------------------
[[0.         0.39130435]
 [0.7826087  1.17391304]
 [1.56521739 1.95652174]]


In [97]:
# flatten an array
print(d2)
print("------------------------------")
d3 = d2.ravel()
print(d3)
print("------------------------------")
print(d3.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
------------------------------
(12,)


In [101]:
d3.shape = (2, 6)
print(d3.shape)
print(d3)
print("------------------------------")
d3 = d3.transpose()
print(d3.shape)
print(d3)


(2, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
------------------------------
(6, 2)
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
